EXPLAIN ALTER SEQUENCE seq1 RESTART;
-- error 42601: syntax error: Cannot EXPLAIN ALTER SEQUENCE

CREATE SEQUENCE seq1;
VALUES NEXT VALUE FOR seq1;
ALTER SEQUENCE seq1 RESTART;
VALUES NEXT VALUE FOR seq1;
-- msg: CREATE SEQUENCE 1
-- COL1: 1
-- msg: ALTER SEQUENCE 1
-- COL1: 1

CREATE SEQUENCE seq1;
VALUES NEXT VALUE FOR seq1;
ALTER SEQUENCE seq1 RESTART WITH 25;
VALUES NEXT VALUE FOR seq1;
-- msg: CREATE SEQUENCE 1
-- COL1: 1
-- msg: ALTER SEQUENCE 1
-- COL1: 25

CREATE SEQUENCE seq1 START WITH 51 INCREMENT BY 2;
ALTER SEQUENCE seq1 RESTART WITH 13;
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
-- msg: CREATE SEQUENCE 1
-- msg: ALTER SEQUENCE 1
-- COL1: 13 COL2: 15

CREATE SEQUENCE seq1 START WITH 51 INCREMENT BY 2;
ALTER SEQUENCE seq1 MAXVALUE 100;
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
-- msg: CREATE SEQUENCE 1
-- msg: ALTER SEQUENCE 1
-- COL1: 51 COL2: 53

CREATE SEQUENCE seq1 INCREMENT BY 2;
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
ALTER SEQUENCE seq1 INCREMENT BY 3;
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
-- msg: CREATE SEQUENCE 1
-- COL1: 1 COL2: 3
-- msg: ALTER SEQUENCE 1
-- COL1: 6 COL2: 9

CREATE SEQUENCE seq1 START WITH 10 INCREMENT BY 5 MAXVALUE 20 CYCLE;
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
ALTER SEQUENCE seq1 NO CYCLE;
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
-- msg: CREATE SEQUENCE 1
-- COL1: 10 COL2: 15
-- COL1: 20 COL2: 1
-- msg: ALTER SEQUENCE 1
-- COL1: 6 COL2: 11
-- error 2200H: sequence generator limit exceeded: PUBLIC.SEQ1

CREATE SEQUENCE seq1 START WITH 10 INCREMENT BY 5 MAXVALUE 20 NO CYCLE;
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
ALTER SEQUENCE seq1 CYCLE;
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
-- msg: CREATE SEQUENCE 1
-- COL1: 10 COL2: 15
-- error 2200H: sequence generator limit exceeded: PUBLIC.SEQ1
-- msg: ALTER SEQUENCE 1
-- COL1: 1 COL2: 6
-- COL1: 11 COL2: 16

CREATE SEQUENCE seq1;
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
ALTER SEQUENCE seq1 RESTART;
VALUES ROW(NEXT VALUE FOR seq1, NEXT VALUE FOR seq1);
-- msg: CREATE SEQUENCE 1
-- COL1: 1 COL2: 2
-- msg: ALTER SEQUENCE 1
-- COL1: 1 COL2: 2
