/* setup */
CREATE TABLE t1 (x INT);
INSERT INTO t1 (x) VALUES (0);

EXPLAIN SELECT 1 AS bob FROM t1;
-- EXPLAIN: TABLE T1 (T1.X INTEGER)
-- EXPLAIN: EXPR (BOB BIGINT)

SELECT 1 AS bob FROM t1;
-- BOB: 1

EXPLAIN SELECT 1 AS "Bob" FROM t1;
-- EXPLAIN: TABLE T1 (T1.X INTEGER)
-- EXPLAIN: EXPR ("Bob" BIGINT)

SELECT 1 AS "Bob" FROM t1;
-- Bob: 1

SELECT 'foo' || 'bar' AS Str FROM t1;
-- STR: foobar

SELECT 1 + 2 AS total1, 3 + 4 AS total2 FROM t1;
-- TOTAL1: 3 TOTAL2: 7
