VALUES 35 BETWEEN 30 AND 40;
-- COL1: TRUE

VALUES 35 BETWEEN 35 AND 40;
-- COL1: TRUE

VALUES 40 BETWEEN 35 AND 40;
-- COL1: TRUE

VALUES 34 BETWEEN 35 AND 40;
-- COL1: FALSE

VALUES 41 BETWEEN 35 AND 40;
-- COL1: FALSE

VALUES 35 BETWEEN 40 AND 30;
-- COL1: FALSE

VALUES 35 BETWEEN ASYMMETRIC 40 AND 30;
-- COL1: FALSE

VALUES 35 BETWEEN SYMMETRIC 40 AND 30;
-- COL1: TRUE

VALUES 35 NOT BETWEEN 30 AND 40;
-- COL1: FALSE

VALUES 35 NOT BETWEEN 35 AND 40;
-- COL1: FALSE

VALUES 40 NOT BETWEEN 35 AND 40;
-- COL1: FALSE

VALUES 34 NOT BETWEEN 35 AND 40;
-- COL1: TRUE

VALUES 41 NOT BETWEEN 35 AND 40;
-- COL1: TRUE

VALUES 35 NOT BETWEEN 40 AND 30;
-- COL1: TRUE

VALUES 35 NOT BETWEEN ASYMMETRIC 40 AND 30;
-- COL1: TRUE

VALUES 35 NOT BETWEEN SYMMETRIC 40 AND 30;
-- COL1: FALSE

VALUES 3.5 BETWEEN 3 AND 4.1;
-- COL1: TRUE

VALUES 3.5 BETWEEN 3.6 AND 4.1;
-- COL1: FALSE

VALUES 'hello' BETWEEN 'hella' AND 'hellr';
-- COL1: TRUE

VALUES 'h' BETWEEN 'x' AND 'y';
-- COL1: FALSE

VALUES 'h' BETWEEN 'ka' AND 'h';
-- COL1: FALSE

VALUES 'h' BETWEEN SYMMETRIC 'ka' AND 'h';
-- COL1: TRUE

VALUES 'i' BETWEEN 'h' AND 'j';
-- COL1: TRUE

EXPLAIN VALUES 'h' NOT BETWEEN SYMMETRIC 'ka' AND 'h';
-- EXPLAIN: VALUES (COL1 BOOLEAN) = ROW('h' NOT BETWEEN SYMMETRIC 'ka' AND 'h')

CREATE TABLE t1 (x INT);
INSERT INTO t1 (x) VALUES (0);
EXPLAIN SELECT * FROM t1 WHERE x NOT BETWEEN SYMMETRIC 'ka' AND 'h';
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- EXPLAIN: TABLE T1 (X INTEGER)
-- EXPLAIN: WHERE X NOT BETWEEN SYMMETRIC 'ka' AND 'h'
