VALUES TRUE;
-- COL1: TRUE

VALUES FALSE;
-- COL1: FALSE

VALUES UNKNOWN;
-- COL1: UNKNOWN

CREATE TABLE foo (x BOOLEAN);
INSERT INTO foo (x) VALUES (NULL);
INSERT INTO foo (x) VALUES (UNKNOWN);
INSERT INTO foo (x) VALUES (TRUE);
INSERT INTO foo (x) VALUES (FALSE);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- msg: INSERT 1
-- msg: INSERT 1
-- msg: INSERT 1
-- X: NULL
-- X: UNKNOWN
-- X: TRUE
-- X: FALSE
