EXPLAIN CREATE SCHEMA foo;
-- error 42601: syntax error: Cannot EXPLAIN CREATE SCHEMA

VALUES CURRENT_SCHEMA;
-- COL1: PUBLIC

CREATE SCHEMA foo;
VALUES CURRENT_SCHEMA;
-- msg: CREATE SCHEMA 1
-- COL1: PUBLIC

CREATE SCHEMA foo;
CREATE SCHEMA foo;
-- msg: CREATE SCHEMA 1
-- error 42P06: duplicate schema: FOO

CREATE SCHEMA foo;
CREATE TABLE foo.bar (baz INT);
INSERT INTO foo.bar (baz) VALUES (123);
SELECT * FROM foo.bar;
VALUES CURRENT_SCHEMA;
-- msg: CREATE SCHEMA 1
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- BAZ: 123
-- COL1: PUBLIC

CREATE SCHEMA absolute;
-- msg: CREATE SCHEMA 1

CREATE SCHEMA ABSOLUTE;
-- msg: CREATE SCHEMA 1
