CREATE TABLE bar (baz BIGINT);
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz BOOLEAN);
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHAR VARYING(10));
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHARACTER VARYING(10));
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHAR(10));
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHARACTER(10));
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHARACTER);
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHAR);
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz DOUBLE PRECISION);
-- msg: CREATE TABLE 1

CREATE TABLE foo (x FLOAT);
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz FLOAT(10));
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz INTEGER);
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz INT);
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz REAL);
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz SMALLINT);
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz VARCHAR(10));
-- msg: CREATE TABLE 1

CREATE TABLE foo (x FLOAT);
CREATE TABLE foo (baz CHARACTER VARYING(10));
-- msg: CREATE TABLE 1
-- error 42P07: duplicate table: PUBLIC.FOO

CREATE TABLE t1 (f1 CHARACTER VARYING(10), f2 FLOAT);
-- msg: CREATE TABLE 1

CREATE TABLE foo (x FLOAT);
CREATE TABLE Foo (baz CHARACTER VARYING(10));
-- msg: CREATE TABLE 1
-- error 42P07: duplicate table: PUBLIC.FOO

CREATE TABLE "foo" (x FLOAT);
CREATE TABLE "Foo" (baz CHARACTER VARYING(10));
-- msg: CREATE TABLE 1
-- msg: CREATE TABLE 1

CREATE TABLE t1 (f1 CHARACTER VARYING(10), f2 FLOAT NOT NULL);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar DATE);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIME);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIME(3));
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIME WITHOUT TIME ZONE);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIME(3) WITHOUT TIME ZONE);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIME WITH TIME ZONE);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIME(3) WITH TIME ZONE);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIMESTAMP);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIMESTAMP(3));
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIMESTAMP WITHOUT TIME ZONE);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIMESTAMP(3) WITHOUT TIME ZONE);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIMESTAMP WITH TIME ZONE);
-- msg: CREATE TABLE 1

CREATE TABLE foo (bar TIMESTAMP(3) WITH TIME ZONE);
-- msg: CREATE TABLE 1

CREATE TABLE foo.bar (baz BIGINT);
-- error 3F000: invalid schema name: FOO

CREATE SCHEMA foo;
CREATE TABLE foo.bar (baz BIGINT);
-- msg: CREATE SCHEMA 1
-- msg: CREATE TABLE 1

CREATE TABLE absolute (baz BIGINT);
-- msg: CREATE TABLE 1

CREATE TABLE ABSOLUTE (baz BIGINT);
-- msg: CREATE TABLE 1

CREATE SCHEMA absolute;
CREATE TABLE absolute.continue (baz BIGINT);
-- msg: CREATE SCHEMA 1
-- msg: CREATE TABLE 1

CREATE SCHEMA absolute;
CREATE TABLE absolute.CONTINUE (baz BIGINT);
-- msg: CREATE SCHEMA 1
-- msg: CREATE TABLE 1

/* connection 1 */
CREATE TABLE foo (bar INT);
/* connection 2 */
CREATE TABLE foo (bar INT);
-- 1: msg: CREATE TABLE 1
-- 2: error 42P07: duplicate table: PUBLIC.FOO

/* connection 1 */
START TRANSACTION;
CREATE TABLE foo (bar INT);
INSERT INTO foo (bar) VALUES (123);
/* connection 2 */
START TRANSACTION;
CREATE TABLE foo (bar VARCHAR(10));
INSERT INTO foo (bar) VALUES ('hello');
/* connection 1 */
COMMIT;
SELECT * FROM foo;
/* connection 2 */
COMMIT;
SELECT * FROM foo;
-- 1: msg: CREATE TABLE 1
-- 2: error 42P07: duplicate table: PUBLIC.FOO
