CREATE TABLE bar (baz BIGINT)
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz BOOLEAN)
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHAR VARYING(10))
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHARACTER VARYING(10))
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHAR(10))
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHARACTER(10))
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHARACTER)
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz CHAR)
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz DOUBLE PRECISION)
-- msg: CREATE TABLE 1

CREATE TABLE foo (a FLOAT)
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz FLOAT(10))
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz INTEGER)
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz INT)
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz REAL)
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz SMALLINT)
-- msg: CREATE TABLE 1

CREATE TABLE bar (baz VARCHAR(10))
-- msg: CREATE TABLE 1

CREATE TABLE foo (a FLOAT)
CREATE TABLE foo (baz CHARACTER VARYING(10))
-- msg: CREATE TABLE 1
-- error: vsql.SQLState42P07: duplicate table: FOO

CREATE TABLE t1 (f1 CHARACTER VARYING(10), f2 FLOAT)
-- msg: CREATE TABLE 1

CREATE TABLE foo (a FLOAT)
CREATE TABLE Foo (baz CHARACTER VARYING(10))
-- msg: CREATE TABLE 1
-- error: vsql.SQLState42P07: duplicate table: FOO

CREATE TABLE "foo" (a FLOAT)
CREATE TABLE "Foo" (baz CHARACTER VARYING(10))
-- msg: CREATE TABLE 1
-- msg: CREATE TABLE 1

CREATE TABLE t1 (f1 CHARACTER VARYING(10) NULL, f2 FLOAT NOT NULL)
-- msg: CREATE TABLE 1
