CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1

CREATE TABLE t1 (x INT);
explain SELECT * FROM t1;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1

CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1 WHERE x > 100;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1
-- EXPLAIN: WHERE X > 100

CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1 OFFSET 5 ROW;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1 OFFSET 5 ROWS

CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1 FETCH FIRST 2 ROW ONLY;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1
-- EXPLAIN: FETCH FIRST 2 ROWS ONLY

CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1 OFFSET 3 ROWS FETCH FIRST 2 ROWS ONLY;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1 OFFSET 3 ROWS
-- EXPLAIN: FETCH FIRST 2 ROWS ONLY

CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1
WHERE x >= 123 AND x <= 456
OFFSET 3 ROWS FETCH FIRST 2 ROWS ONLY;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1 OFFSET 3 ROWS
-- EXPLAIN: WHERE X >= 123 AND X <= 456
-- EXPLAIN: FETCH FIRST 2 ROWS ONLY

/* set foo 2 */
CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1 WHERE x = :foo;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1
-- EXPLAIN: WHERE X = 2

EXPLAIN CREATE TABLE t1 (x INT);
-- error 42601: syntax error: Cannot EXPLAIN CREATE TABLE

EXPLAIN DROP TABLE t1;
-- error 42601: syntax error: Cannot EXPLAIN DROP TABLE

EXPLAIN INSERT INTO t1 (x) VALUES (0);
-- error 42601: syntax error: Cannot EXPLAIN INSERT

CREATE TABLE t1 (x INT);
EXPLAIN DELETE FROM t1;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1

CREATE TABLE t1 (x INT);
EXPLAIN DELETE FROM t1 WHERE x = 35;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1
-- EXPLAIN: WHERE X = 35

CREATE TABLE t1 (x INT);
EXPLAIN UPDATE t1 SET x = 1;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1

CREATE TABLE t1 (x INT);
EXPLAIN UPDATE t1 SET x = 1 WHERE x = 35;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE T1
-- EXPLAIN: WHERE X = 35
