CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER)

CREATE TABLE t1 (x INT);
explain SELECT * FROM t1;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER)

CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1 WHERE x > 100;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: WHERE X > 100
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER)

CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1 OFFSET 5 ROW;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: OFFSET 5 ROWS
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER)

CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1 FETCH FIRST 2 ROW ONLY;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: FETCH FIRST 2 ROWS ONLY
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER)

CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1 OFFSET 3 ROWS FETCH FIRST 2 ROWS ONLY;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: OFFSET 3 ROWS FETCH FIRST 2 ROWS ONLY
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER)

CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1
WHERE x >= 123 AND x <= 456
OFFSET 3 ROWS FETCH FIRST 2 ROWS ONLY;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: WHERE X >= 123 AND X <= 456
-- EXPLAIN: OFFSET 3 ROWS FETCH FIRST 2 ROWS ONLY
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER)

/* set foo 2 */
CREATE TABLE t1 (x INT);
EXPLAIN SELECT * FROM t1 WHERE x = :foo;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: WHERE X = 2e0
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER)

EXPLAIN CREATE TABLE t1 (x INT);
-- error 42601: syntax error: Cannot EXPLAIN CREATE TABLE

EXPLAIN DROP TABLE t1;
-- error 42601: syntax error: Cannot EXPLAIN DROP TABLE

EXPLAIN INSERT INTO t1 (x) VALUES (0);
-- error 42601: syntax error: Cannot EXPLAIN INSERT

CREATE TABLE t1 (x INT);
EXPLAIN DELETE FROM t1;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)

CREATE TABLE t1 (x INT);
EXPLAIN DELETE FROM t1 WHERE x = 35;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: WHERE X = 35

CREATE TABLE t1 (x INT);
EXPLAIN UPDATE t1 SET x = 1;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)

CREATE TABLE t1 (x INT);
EXPLAIN UPDATE t1 SET x = 1 WHERE x = 35;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: WHERE X = 35

CREATE TABLE t1 (x INT, PRIMARY KEY(x));
EXPLAIN SELECT * FROM t1;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER)
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER)

CREATE TABLE t1 (x INT, PRIMARY KEY(x));
EXPLAIN SELECT * FROM t1 WHERE x = 10;
-- msg: CREATE TABLE 1
-- EXPLAIN: PRIMARY KEY ":memory:".PUBLIC.T1 (X INTEGER) BETWEEN 10 AND 10
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER)

CREATE TABLE t1 (x INT, b INT, PRIMARY KEY(x));
EXPLAIN SELECT * FROM t1 WHERE b = 10;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER, B INTEGER)
-- EXPLAIN: WHERE B = 10
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER, ":memory:".PUBLIC.T1.B INTEGER)

CREATE TABLE t1 (x INT, b INT, PRIMARY KEY(x));
EXPLAIN SELECT * FROM t1 WHERE x = 10 AND b = 20;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.T1 (X INTEGER, B INTEGER)
-- EXPLAIN: WHERE X = 10 AND B = 20
-- EXPLAIN: EXPR (":memory:".PUBLIC.T1.X INTEGER, ":memory:".PUBLIC.T1.B INTEGER)

EXPLAIN START TRANSACTION;
-- error 42601: syntax error: Cannot EXPLAIN START TRANSACTION

EXPLAIN COMMIT;
-- error 42601: syntax error: Cannot EXPLAIN COMMIT

EXPLAIN ROLLBACK;
-- error 42601: syntax error: Cannot EXPLAIN ROLLBACK
