/* setup */
CREATE TABLE foo (x FLOAT, y VARCHAR(32));
INSERT INTO foo (x, y) VALUES (1.234, 'hello');
INSERT INTO foo (x, y) VALUES (12.34, 'hello');
INSERT INTO foo (x, y) VALUES (1.234, 'world');
INSERT INTO foo (x, y) VALUES (5.6, 'world');
INSERT INTO foo (x, y) VALUES (5.6, 'world');

EXPLAIN SELECT x FROM foo GROUP BY x;
-- EXPLAIN: TABLE FOO (X DOUBLE PRECISION)
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: GROUP BY X ()

SELECT x FROM foo GROUP BY x;
-- X: 1.234
-- X: 5.6
-- X: 12.34

EXPLAIN SELECT x, count(*) FROM foo GROUP BY x;
-- EXPLAIN: TABLE FOO (X DOUBLE PRECISION, COL2 INTEGER)
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: GROUP BY X (COUNT(*) AS COL2)

SELECT x, count(*) FROM foo GROUP BY x;
-- X: 1.234 COL2: 2
-- X: 5.6 COL2: 2
-- X: 12.34 COL2: 1

EXPLAIN SELECT count(*), x FROM foo GROUP BY x;
-- EXPLAIN: TABLE FOO (COL1 INTEGER, X DOUBLE PRECISION)
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: GROUP BY X (COUNT(*) AS COL1)

SELECT count(*), x FROM foo GROUP BY x;
-- COL1: 2 X: 1.234
-- COL1: 2 X: 5.6
-- COL1: 1 X: 12.34

EXPLAIN SELECT x, y FROM foo GROUP BY x, y;
-- EXPLAIN: TABLE FOO (X DOUBLE PRECISION, Y CHARACTER VARYING(32))
-- EXPLAIN: ORDER BY X ASC, Y ASC
-- EXPLAIN: GROUP BY X, Y ()

SELECT x, y FROM foo GROUP BY x, y;
-- X: 1.234 Y: hello
-- X: 1.234 Y: world
-- X: 5.6 Y: world
-- X: 12.34 Y: hello

EXPLAIN SELECT y, x FROM foo GROUP BY x, y;
-- EXPLAIN: TABLE FOO (Y CHARACTER VARYING(32), X DOUBLE PRECISION)
-- EXPLAIN: ORDER BY X ASC, Y ASC
-- EXPLAIN: GROUP BY Y, X ()

SELECT y, x FROM foo GROUP BY x, y;
-- Y: hello X: 1.234
-- Y: world X: 1.234
-- Y: world X: 5.6
-- Y: hello X: 12.34

EXPLAIN SELECT x, y FROM foo GROUP BY y, x;
-- EXPLAIN: TABLE FOO (X DOUBLE PRECISION, Y CHARACTER VARYING(32))
-- EXPLAIN: ORDER BY Y ASC, X ASC
-- EXPLAIN: GROUP BY X, Y ()

SELECT x, y FROM foo GROUP BY y, x;
-- X: 1.234 Y: hello
-- X: 12.34 Y: hello
-- X: 1.234 Y: world
-- X: 5.6 Y: world

EXPLAIN SELECT x + 1, x FROM foo GROUP BY x;
-- EXPLAIN: TABLE FOO (COL1 DOUBLE PRECISION, X DOUBLE PRECISION)
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: GROUP BY X + 1, X ()

SELECT x + 1, x FROM foo GROUP BY x;
-- COL1: 2.234 X: 1.234
-- COL1: 6.6 X: 5.6
-- COL1: 13.34 X: 12.34

EXPLAIN SELECT x + 1 FROM foo GROUP BY x;
-- error 42601: syntax error: The expression X from the GROUP BY must appear in SELECT expressions.

SELECT x + 1 FROM foo GROUP BY x;
-- error 42601: syntax error: The expression X from the GROUP BY must appear in SELECT expressions.

EXPLAIN SELECT x, count(x) FROM foo GROUP BY x;
-- EXPLAIN: TABLE FOO (X DOUBLE PRECISION, COL2 INTEGER)
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: GROUP BY X (COUNT(X) AS COL2)

SELECT x, count(x) FROM foo GROUP BY x;
-- X: 1.234 COL2: 2
-- X: 5.6 COL2: 2
-- X: 12.34 COL2: 1

EXPLAIN SELECT y, min(x) FROM foo GROUP BY y;
-- EXPLAIN: TABLE FOO (Y CHARACTER VARYING(32), COL2 DOUBLE PRECISION)
-- EXPLAIN: ORDER BY Y ASC
-- EXPLAIN: GROUP BY Y (MIN(X) AS COL2)

SELECT y, min(x) FROM foo GROUP BY y;
-- Y: hello COL2: 1.234
-- Y: world COL2: 1.234

EXPLAIN SELECT y, max(x) AS largest FROM foo GROUP BY y;
-- EXPLAIN: TABLE FOO (Y CHARACTER VARYING(32), LARGEST DOUBLE PRECISION)
-- EXPLAIN: ORDER BY Y ASC
-- EXPLAIN: GROUP BY Y (MAX(X) AS LARGEST)

SELECT y, max(x) AS largest FROM foo GROUP BY y;
-- Y: hello LARGEST: 12.34
-- Y: world LARGEST: 5.6

SELECT y, sum(x) FROM foo GROUP BY y;
-- Y: hello COL2: 13.574
-- Y: world COL2: 12.434

SELECT y, avg(x) FROM foo GROUP BY y;
-- Y: hello COL2: 6.787
-- Y: world COL2: 4.144667

EXPLAIN SELECT y, avg(x) FROM foo WHERE y = 'hello' GROUP BY y;
-- EXPLAIN: TABLE FOO (Y CHARACTER VARYING(32), COL2 DOUBLE PRECISION)
-- EXPLAIN: WHERE Y = 'hello'
-- EXPLAIN: ORDER BY Y ASC
-- EXPLAIN: GROUP BY Y (AVG(X) AS COL2)

SELECT y, avg(x) FROM foo WHERE y = 'hello' GROUP BY y;
-- Y: hello COL2: 6.787

EXPLAIN SELECT count(*) FROM foo;
-- EXPLAIN: TABLE FOO (COL1 INTEGER)
-- EXPLAIN: GROUP BY (COUNT(*) AS COL1)

SELECT count(*) FROM foo;
-- COL1: 5

SELECT count(x) FROM foo;
-- COL1: 5

SELECT min(x) FROM foo;
-- COL1: 1.234

SELECT max(x) FROM foo;
-- COL1: 12.34

SELECT avg(x) FROM foo;
-- COL1: 5.2016

SELECT sum(x) FROM foo;
-- COL1: 26.008

SELECT min(x), max(x) FROM foo;
-- COL1: 1.234 COL2: 12.34

SELECT avg(x * 2) FROM foo;
-- COL1: 10.4032

EXPLAIN SELECT x FROM foo GROUP BY x FETCH FIRST 2 ROWS ONLY;
-- EXPLAIN: TABLE FOO (X DOUBLE PRECISION)
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: GROUP BY X ()
-- EXPLAIN: FETCH FIRST 2 ROWS ONLY

SELECT x FROM foo GROUP BY x FETCH FIRST 2 ROWS ONLY;
-- X: 1.234
-- X: 5.6

EXPLAIN SELECT x FROM foo GROUP BY x 
OFFSET 1 ROW
FETCH FIRST 2 ROWS ONLY;
-- EXPLAIN: TABLE FOO (X DOUBLE PRECISION)
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: GROUP BY X ()
-- EXPLAIN: OFFSET 1 ROWS FETCH FIRST 2 ROWS ONLY

SELECT x FROM foo GROUP BY x 
OFFSET 1 ROW
FETCH FIRST 2 ROWS ONLY;
-- X: 5.6
-- X: 12.34

EXPLAIN SELECT x FROM foo GROUP BY x ORDER BY x DESC FETCH FIRST 2 ROWS ONLY;
-- EXPLAIN: TABLE FOO (X DOUBLE PRECISION)
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: GROUP BY X ()
-- EXPLAIN: ORDER BY X DESC
-- EXPLAIN: FETCH FIRST 2 ROWS ONLY

SELECT x FROM foo GROUP BY x ORDER BY x DESC FETCH FIRST 2 ROWS ONLY;
-- X: 12.34
-- X: 5.6

EXPLAIN SELECT x FROM foo
GROUP BY x
ORDER BY x DESC
OFFSET 1 ROW
FETCH FIRST 2 ROWS ONLY;
-- EXPLAIN: TABLE FOO (X DOUBLE PRECISION)
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: GROUP BY X ()
-- EXPLAIN: ORDER BY X DESC
-- EXPLAIN: OFFSET 1 ROWS FETCH FIRST 2 ROWS ONLY

SELECT x FROM foo
GROUP BY x
ORDER BY x DESC
OFFSET 1 ROW
FETCH FIRST 2 ROWS ONLY;
-- X: 5.6
-- X: 1.234

EXPLAIN SELECT y, min(x) * avg(x) FROM foo GROUP BY y;
-- error 42601: syntax error: nested aggregate functions are not supported: MIN(X) * AVG(X)

SELECT y, min(x) * avg(x) FROM foo GROUP BY y;
-- error 42601: syntax error: nested aggregate functions are not supported: MIN(X) * AVG(X)
