/* setup */
CREATE TABLE t1 (x VARCHAR(64));
INSERT INTO t1 (x) VALUES ('hello Hello');

SELECT CHAR_LENGTH(x) FROM t1;
-- COL1: 11

SELECT CHARACTER_LENGTH(x) FROM t1;
-- COL1: 11

SELECT OCTET_LENGTH(x) FROM t1;
-- COL1: 11

SELECT CHAR_LENGTH('😊£') FROM t1;
-- COL1: 2

SELECT OCTET_LENGTH('😊£') FROM t1;
-- COL1: 6
