CREATE SEQUENCE seq1;
CREATE TABLE bar (baz INTEGER);
INSERT INTO bar (baz) VALUES (NEXT VALUE FOR seq1);
INSERT INTO bar (baz) VALUES (NEXT VALUE FOR seq1);
SELECT * FROM bar;
UPDATE bar SET baz = NEXT VALUE FOR seq1;
SELECT * FROM bar;
-- msg: CREATE SEQUENCE 1
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- msg: INSERT 1
-- BAZ: 1
-- BAZ: 2
-- msg: UPDATE 2
-- BAZ: 3
-- BAZ: 4

/* connection 1 */
CREATE SEQUENCE seq1;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
/* connection 2 */
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
/* connection 3 */
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
-- 1: msg: CREATE SEQUENCE 1
-- 1: COL1: 1 COL2: 2
-- 2: COL1: 3 COL2: 4
-- 3: COL1: 5 COL2: 6

/* connection 1 */
CREATE SEQUENCE seq1;
START TRANSACTION;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
COMMIT;
/* connection 2 */
START TRANSACTION;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
COMMIT;
/* connection 3 */
START TRANSACTION;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
COMMIT;
-- 1: msg: CREATE SEQUENCE 1
-- 1: msg: START TRANSACTION
-- 1: COL1: 1 COL2: 2
-- 1: msg: COMMIT
-- 2: msg: START TRANSACTION
-- 2: COL1: 3 COL2: 4
-- 2: msg: COMMIT
-- 3: msg: START TRANSACTION
-- 3: COL1: 5 COL2: 6
-- 3: msg: COMMIT

/* connection 1 */
CREATE SEQUENCE seq1;
START TRANSACTION;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
ROLLBACK;
/* connection 2 */
START TRANSACTION;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
ROLLBACK;
/* connection 3 */
START TRANSACTION;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
ROLLBACK;
-- 1: msg: CREATE SEQUENCE 1
-- 1: msg: START TRANSACTION
-- 1: COL1: 1 COL2: 2
-- 1: msg: ROLLBACK
-- 2: msg: START TRANSACTION
-- 2: COL1: 3 COL2: 4
-- 2: msg: ROLLBACK
-- 3: msg: START TRANSACTION
-- 3: COL1: 5 COL2: 6
-- 3: msg: ROLLBACK

/* connection 1 */
CREATE SEQUENCE seq1;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
START TRANSACTION;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
ROLLBACK;
/* connection 2 */
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
START TRANSACTION;
/* connection 1 */
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
/* connection 2 */
COMMIT;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
-- 1: msg: CREATE SEQUENCE 1
-- 1: COL1: 1 COL2: 2
-- 1: msg: START TRANSACTION
-- 1: COL1: 3 COL2: 4
-- 1: msg: ROLLBACK
-- 2: COL1: 5 COL2: 6
-- 2: msg: START TRANSACTION
-- 1: COL1: 7 COL2: 8
-- 2: msg: COMMIT
-- 2: COL1: 9 COL2: 10

/* connection 1 */
CREATE SEQUENCE seq1;
START TRANSACTION;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
/* connection 2 */
START TRANSACTION;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
/* connection 3 */
START TRANSACTION;
VALUES NEXT VALUE FOR seq1, NEXT VALUE FOR seq1;
/* connection 1 */
COMMIT;
/* connection 2 */
COMMIT;
/* connection 3 */
COMMIT;
-- 1: msg: CREATE SEQUENCE 1
-- 1: msg: START TRANSACTION
-- 1: COL1: 1 COL2: 2
-- 2: msg: START TRANSACTION
-- 2: COL1: 3 COL2: 4
-- 3: msg: START TRANSACTION
-- 3: COL1: 5 COL2: 6
-- 1: msg: COMMIT
-- 2: msg: COMMIT
-- 3: msg: COMMIT
