EXPLAIN VALUES NULLIF(TRUE, TRUE);
-- EXPLAIN: VALUES (COL1 BOOLEAN) = ROW(NULLIF(TRUE, TRUE))

VALUES NULLIF(123, 123);
-- COL1: NULL

VALUES NULLIF(123, 456);
-- COL1: 123

VALUES NULLIF(123, 'hello');
-- error 42804: data type mismatch in NULLIF: expected NUMERIC but got CHARACTER VARYING
