VALUES 'a' IS NULL;
-- COL1: FALSE

VALUES 'a' IS NOT NULL;
-- COL1: TRUE

VALUES 1.23 IS NULL;
-- COL1: FALSE

VALUES 1.23 IS NOT NULL;
-- COL1: TRUE

VALUES 123 IS NULL;
-- COL1: FALSE

VALUES 123 IS NOT NULL;
-- COL1: TRUE

CREATE TABLE foo (num FLOAT);
INSERT INTO foo (num) VALUES (13);
INSERT INTO foo (num) VALUES (NULL);
INSERT INTO foo (num) VALUES (35);
VALUES 'is null';
SELECT * FROM foo WHERE num IS NULL;
VALUES 'is not null';
SELECT * FROM foo WHERE num IS NOT NULL;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- msg: INSERT 1
-- msg: INSERT 1
-- COL1: is null
-- NUM: NULL
-- COL1: is not null
-- NUM: 13
-- NUM: 35

CREATE TABLE foo (x BOOLEAN);
INSERT INTO foo (x) VALUES (NULL);
INSERT INTO foo (x) VALUES (UNKNOWN);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- msg: INSERT 1
-- X: UNKNOWN
-- X: UNKNOWN

CREATE TABLE foo (x BIGINT);
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x DOUBLE PRECISION);
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x INTEGER);
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x REAL);
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x SMALLINT);
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x CHARACTER VARYING(10));
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x CHARACTER(10));
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x DATE);
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x TIME(6) WITH TIME ZONE);
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x TIME(6) WITHOUT TIME ZONE);
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x TIMESTAMP(6) WITH TIME ZONE);
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL

CREATE TABLE foo (x TIMESTAMP(6) WITHOUT TIME ZONE);
INSERT INTO foo (x) VALUES (NULL);
SELECT * FROM foo;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- X: NULL
