VALUES 'a' IS NULL;
-- COL1: FALSE

VALUES 'a' IS NOT NULL;
-- COL1: TRUE

VALUES 1.23 IS NULL;
-- COL1: FALSE

VALUES 1.23 IS NOT NULL;
-- COL1: TRUE

VALUES 123 IS NULL;
-- COL1: FALSE

VALUES 123 IS NOT NULL;
-- COL1: TRUE

CREATE TABLE foo (num FLOAT);
INSERT INTO foo (num) VALUES (13);
INSERT INTO foo (num) VALUES (NULL);
INSERT INTO foo (num) VALUES (35);
VALUES 'is null';
SELECT * FROM foo WHERE num IS NULL;
VALUES 'is not null';
SELECT * FROM foo WHERE num IS NOT NULL;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- msg: INSERT 1
-- msg: INSERT 1
-- COL1: is null
-- NUM: NULL
-- COL1: is not null
-- NUM: 13
-- NUM: 35
