/* setup */
CREATE TABLE t1 (x INT);
INSERT INTO t1 (x) VALUES (0);

SELECT 'a' IS NULL FROM t1;
-- COL1: FALSE

SELECT 'a' IS NOT NULL FROM t1;
-- COL1: TRUE

SELECT 1.23 IS NULL FROM t1;
-- COL1: FALSE

SELECT 1.23 IS NOT NULL FROM t1;
-- COL1: TRUE

SELECT 123 IS NULL FROM t1;
-- COL1: FALSE

SELECT 123 IS NOT NULL FROM t1;
-- COL1: TRUE

CREATE TABLE foo (num FLOAT);
INSERT INTO foo (num) VALUES (13);
INSERT INTO foo (num) VALUES (NULL);
INSERT INTO foo (num) VALUES (35);
SELECT 'is null' FROM t1;
SELECT * FROM foo WHERE num IS NULL;
SELECT 'is not null' FROM t1;
SELECT * FROM foo WHERE num IS NOT NULL;
-- msg: CREATE TABLE 1
-- msg: INSERT 1
-- msg: INSERT 1
-- msg: INSERT 1
-- COL1: is null
-- NUM: NULL
-- COL1: is not null
-- NUM: 13
-- NUM: 35
