/* setup */
CREATE TABLE foo (x FLOAT, y VARCHAR(32));
INSERT INTO foo (x, y) VALUES (1.234, 'hi');
INSERT INTO foo (x, y) VALUES (12.34, 'there');
INSERT INTO foo (x, y) VALUES (0.1234, 'hi');
INSERT INTO foo (x, y) VALUES (5.6, 'bar');

EXPLAIN SELECT * FROM foo ORDER BY x;
-- EXPLAIN: TABLE ":memory:".PUBLIC.FOO (X DOUBLE PRECISION, Y CHARACTER VARYING(32))
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: EXPR (":memory:".PUBLIC.FOO.X DOUBLE PRECISION, ":memory:".PUBLIC.FOO.Y CHARACTER VARYING(32))

SELECT * FROM foo ORDER BY x;
-- X: 0.1234e0 Y: hi
-- X: 1.234e0 Y: hi
-- X: 5.6e0 Y: bar
-- X: 12.34e0 Y: there

EXPLAIN SELECT * FROM foo ORDER BY x ASC;
-- EXPLAIN: TABLE ":memory:".PUBLIC.FOO (X DOUBLE PRECISION, Y CHARACTER VARYING(32))
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: EXPR (":memory:".PUBLIC.FOO.X DOUBLE PRECISION, ":memory:".PUBLIC.FOO.Y CHARACTER VARYING(32))

EXPLAIN SELECT * FROM foo ORDER BY x DESC;
-- EXPLAIN: TABLE ":memory:".PUBLIC.FOO (X DOUBLE PRECISION, Y CHARACTER VARYING(32))
-- EXPLAIN: ORDER BY X DESC
-- EXPLAIN: EXPR (":memory:".PUBLIC.FOO.X DOUBLE PRECISION, ":memory:".PUBLIC.FOO.Y CHARACTER VARYING(32))

SELECT * FROM foo ORDER BY x DESC;
-- X: 12.34e0 Y: there
-- X: 5.6e0 Y: bar
-- X: 1.234e0 Y: hi
-- X: 0.1234e0 Y: hi

SELECT * FROM foo ORDER BY y;
-- X: 5.6e0 Y: bar
-- X: 1.234e0 Y: hi
-- X: 0.1234e0 Y: hi
-- X: 12.34e0 Y: there

EXPLAIN SELECT * FROM foo ORDER BY y, x;
-- EXPLAIN: TABLE ":memory:".PUBLIC.FOO (X DOUBLE PRECISION, Y CHARACTER VARYING(32))
-- EXPLAIN: ORDER BY Y ASC, X ASC
-- EXPLAIN: EXPR (":memory:".PUBLIC.FOO.X DOUBLE PRECISION, ":memory:".PUBLIC.FOO.Y CHARACTER VARYING(32))

SELECT * FROM foo ORDER BY y, x;
-- X: 5.6e0 Y: bar
-- X: 0.1234e0 Y: hi
-- X: 1.234e0 Y: hi
-- X: 12.34e0 Y: there

SELECT * FROM foo ORDER BY y, x DESC;
-- X: 5.6e0 Y: bar
-- X: 1.234e0 Y: hi
-- X: 0.1234e0 Y: hi
-- X: 12.34e0 Y: there

SELECT * FROM foo ORDER BY x DESC, y;
-- X: 12.34e0 Y: there
-- X: 5.6e0 Y: bar
-- X: 1.234e0 Y: hi
-- X: 0.1234e0 Y: hi

EXPLAIN SELECT * FROM foo ORDER BY ABS(10 - x);
-- EXPLAIN: TABLE ":memory:".PUBLIC.FOO (X DOUBLE PRECISION, Y CHARACTER VARYING(32))
-- EXPLAIN: ORDER BY ABS(10 - X) ASC
-- EXPLAIN: EXPR (":memory:".PUBLIC.FOO.X DOUBLE PRECISION, ":memory:".PUBLIC.FOO.Y CHARACTER VARYING(32))

SELECT * FROM foo ORDER BY ABS(10e0 - x);
-- X: 12.34e0 Y: there
-- X: 5.6e0 Y: bar
-- X: 1.234e0 Y: hi
-- X: 0.1234e0 Y: hi

SELECT * FROM foo ORDER BY ABS(10e0 - x) DESC;
-- X: 0.1234e0 Y: hi
-- X: 1.234e0 Y: hi
-- X: 5.6e0 Y: bar
-- X: 12.34e0 Y: there

SELECT * FROM foo
ORDER BY y, x
OFFSET 0 ROWS;
-- X: 5.6e0 Y: bar
-- X: 0.1234e0 Y: hi
-- X: 1.234e0 Y: hi
-- X: 12.34e0 Y: there

EXPLAIN SELECT * FROM foo
ORDER BY y, x
OFFSET 2 ROW;
-- EXPLAIN: TABLE ":memory:".PUBLIC.FOO (X DOUBLE PRECISION, Y CHARACTER VARYING(32))
-- EXPLAIN: ORDER BY Y ASC, X ASC
-- EXPLAIN: OFFSET 2 ROWS
-- EXPLAIN: EXPR (":memory:".PUBLIC.FOO.X DOUBLE PRECISION, ":memory:".PUBLIC.FOO.Y CHARACTER VARYING(32))

SELECT * FROM foo
ORDER BY y, x
OFFSET 2 ROW;
-- X: 1.234e0 Y: hi
-- X: 12.34e0 Y: there

SELECT * FROM foo
ORDER BY y, x
OFFSET 50 ROW;

SELECT * FROM foo
ORDER BY y, x
FETCH FIRST 2 ROWS ONLY;
-- X: 5.6e0 Y: bar
-- X: 0.1234e0 Y: hi

EXPLAIN SELECT * FROM foo
ORDER BY y, x
OFFSET 1 ROW
FETCH FIRST 2 ROWS ONLY;
-- EXPLAIN: TABLE ":memory:".PUBLIC.FOO (X DOUBLE PRECISION, Y CHARACTER VARYING(32))
-- EXPLAIN: ORDER BY Y ASC, X ASC
-- EXPLAIN: OFFSET 1 ROWS FETCH FIRST 2 ROWS ONLY
-- EXPLAIN: EXPR (":memory:".PUBLIC.FOO.X DOUBLE PRECISION, ":memory:".PUBLIC.FOO.Y CHARACTER VARYING(32))

SELECT * FROM foo
ORDER BY y, x
OFFSET 1 ROW
FETCH FIRST 2 ROWS ONLY;
-- X: 0.1234e0 Y: hi
-- X: 1.234e0 Y: hi

SELECT * FROM foo
ORDER BY y, x
OFFSET 10 ROWS
FETCH FIRST 2 ROWS ONLY;

/* set offset_num 1 */
/* set row_num 2 */
SELECT * FROM foo
ORDER BY y, x
OFFSET :offset_num ROW
FETCH FIRST :row_num ROWS ONLY;
-- X: 0.1234e0 Y: hi
-- X: 1.234e0 Y: hi

CREATE TABLE bar (x FLOAT, y VARCHAR(32));
EXPLAIN SELECT * FROM bar ORDER BY x;
-- msg: CREATE TABLE 1
-- EXPLAIN: TABLE ":memory:".PUBLIC.BAR (X DOUBLE PRECISION, Y CHARACTER VARYING(32))
-- EXPLAIN: ORDER BY X ASC
-- EXPLAIN: EXPR (":memory:".PUBLIC.BAR.X DOUBLE PRECISION, ":memory:".PUBLIC.BAR.Y CHARACTER VARYING(32))

CREATE TABLE bar (x FLOAT, y VARCHAR(32));
SELECT * FROM bar ORDER BY x;
-- msg: CREATE TABLE 1
