/* setup */
CREATE TABLE foo (num FLOAT);
INSERT INTO foo (num) VALUES (13);
INSERT INTO foo (num) VALUES (27);
INSERT INTO foo (num) VALUES (35);

EXPLAIN SELECT * FROM foo WHERE num = 27.0;
-- EXPLAIN: TABLE ":memory:".PUBLIC.FOO (NUM DOUBLE PRECISION)
-- EXPLAIN: WHERE NUM = 27
-- EXPLAIN: EXPR (":memory:".PUBLIC.FOO.NUM DOUBLE PRECISION)

SELECT * FROM foo WHERE num = 27.0;
-- NUM: 27e0

SELECT * FROM foo WHERE num <> 13.0;
-- NUM: 27e0
-- NUM: 35e0

SELECT * FROM foo WHERE num > 27.0;
-- NUM: 35e0

SELECT * FROM foo WHERE num >= 27.0;
-- NUM: 27e0
-- NUM: 35e0

SELECT * FROM foo WHERE num < 27.0;
-- NUM: 13e0

EXPLAIN SELECT * FROM foo WHERE num <= 27.0;
-- EXPLAIN: TABLE ":memory:".PUBLIC.FOO (NUM DOUBLE PRECISION)
-- EXPLAIN: WHERE NUM <= 27
-- EXPLAIN: EXPR (":memory:".PUBLIC.FOO.NUM DOUBLE PRECISION)

SELECT * FROM foo WHERE num <= 27.0;
-- NUM: 13e0
-- NUM: 27e0

EXPLAIN SELECT * FROM foo WHERE foo.num = 27.0;
-- EXPLAIN: TABLE ":memory:".PUBLIC.FOO (NUM DOUBLE PRECISION)
-- EXPLAIN: WHERE FOO.NUM = 27
-- EXPLAIN: EXPR (":memory:".PUBLIC.FOO.NUM DOUBLE PRECISION)

SELECT * FROM foo WHERE foo.num = 27.0;
-- NUM: 27e0
