EXPLAIN SET SCHEMA 'foo';
-- error 42601: syntax error: Cannot EXPLAIN SET SCHEMA

CREATE SCHEMA foo;
VALUES CURRENT_SCHEMA;
SET SCHEMA 'FOO';
VALUES CURRENT_SCHEMA;
-- msg: CREATE SCHEMA 1
-- COL1: PUBLIC
-- msg: SET SCHEMA 1
-- COL1: FOO

SET SCHEMA 'foo';
VALUES CURRENT_SCHEMA;
-- error 3F000: invalid schema name: foo
-- COL1: PUBLIC
