/* setup */
CREATE TABLE PUBLIC.t1 (x INT, y VARCHAR(16));
INSERT INTO t1 (x, y) VALUES (123, 'hello');
INSERT INTO t1 (x, y) VALUES (456, 'world');

EXPLAIN SELECT * FROM (SELECT * FROM t1);
-- EXPLAIN: $1:
-- EXPLAIN:   TABLE ":memory:".PUBLIC.T1 (X INTEGER, Y CHARACTER VARYING(16))
-- EXPLAIN:   EXPR (":memory:".PUBLIC.T1.X INTEGER, ":memory:".PUBLIC.T1.Y CHARACTER VARYING(16))
-- EXPLAIN: TABLE $1 (X INTEGER, Y CHARACTER VARYING(16))
-- EXPLAIN: EXPR ($1.X INTEGER, $1.Y CHARACTER VARYING(16))

EXPLAIN SELECT * FROM (SELECT x FROM t1);
-- EXPLAIN: $1:
-- EXPLAIN:   TABLE ":memory:".PUBLIC.T1 (X INTEGER, Y CHARACTER VARYING(16))
-- EXPLAIN:   EXPR (X INTEGER)
-- EXPLAIN: TABLE $1 (X INTEGER)
-- EXPLAIN: EXPR ($1.X INTEGER)

EXPLAIN SELECT x FROM (SELECT x FROM t1);
-- EXPLAIN: $1:
-- EXPLAIN:   TABLE ":memory:".PUBLIC.T1 (X INTEGER, Y CHARACTER VARYING(16))
-- EXPLAIN:   EXPR (X INTEGER)
-- EXPLAIN: TABLE $1 (X INTEGER)
-- EXPLAIN: EXPR (X INTEGER)

SELECT x FROM (SELECT x FROM t1);
-- X: 123
-- X: 456

SELECT * FROM (SELECT x FROM t1);
-- X: 123
-- X: 456

EXPLAIN SELECT x, y FROM (SELECT x, y FROM t1);
-- EXPLAIN: $1:
-- EXPLAIN:   TABLE ":memory:".PUBLIC.T1 (X INTEGER, Y CHARACTER VARYING(16))
-- EXPLAIN:   EXPR (X INTEGER, Y CHARACTER VARYING)
-- EXPLAIN: TABLE $1 (X INTEGER, Y CHARACTER VARYING)
-- EXPLAIN: EXPR (X INTEGER, Y CHARACTER VARYING)

SELECT x, y FROM (SELECT x, y FROM t1);
-- X: 123 Y: hello
-- X: 456 Y: world

EXPLAIN SELECT y FROM (SELECT x, y FROM t1);
-- EXPLAIN: $1:
-- EXPLAIN:   TABLE ":memory:".PUBLIC.T1 (X INTEGER, Y CHARACTER VARYING(16))
-- EXPLAIN:   EXPR (X INTEGER, Y CHARACTER VARYING)
-- EXPLAIN: TABLE $1 (X INTEGER, Y CHARACTER VARYING)
-- EXPLAIN: EXPR (Y CHARACTER VARYING)

SELECT y FROM (SELECT x, y FROM t1);
-- Y: hello
-- Y: world

EXPLAIN SELECT * FROM (SELECT x + char_length(y) FROM t1);
-- EXPLAIN: $1:
-- EXPLAIN:   TABLE ":memory:".PUBLIC.T1 (X INTEGER, Y CHARACTER VARYING(16))
-- EXPLAIN:   EXPR (COL1 INTEGER)
-- EXPLAIN: TABLE $1 (COL1 INTEGER)
-- EXPLAIN: EXPR ($1.COL1 INTEGER)

SELECT * FROM (SELECT x + char_length(y) FROM t1);
-- COL1: 128
-- COL1: 461

EXPLAIN SELECT * FROM (SELECT x + char_length(y) AS foo FROM t1);
-- EXPLAIN: $1:
-- EXPLAIN:   TABLE ":memory:".PUBLIC.T1 (X INTEGER, Y CHARACTER VARYING(16))
-- EXPLAIN:   EXPR (FOO INTEGER)
-- EXPLAIN: TABLE $1 (FOO INTEGER)
-- EXPLAIN: EXPR ($1.FOO INTEGER)

SELECT * FROM (SELECT x + char_length(y) AS foo FROM t1);
-- FOO: 128
-- FOO: 461

EXPLAIN SELECT foo AS bar FROM (SELECT x + char_length(y) AS foo FROM t1);
-- EXPLAIN: $1:
-- EXPLAIN:   TABLE ":memory:".PUBLIC.T1 (X INTEGER, Y CHARACTER VARYING(16))
-- EXPLAIN:   EXPR (FOO INTEGER)
-- EXPLAIN: TABLE $1 (FOO INTEGER)
-- EXPLAIN: EXPR (BAR INTEGER)

SELECT foo AS bar FROM (SELECT x + char_length(y) AS foo FROM t1);
-- BAR: 128
-- BAR: 461
