EXPLAIN VALUES SUBSTRING('hello' FROM 3);
-- EXPLAIN: VALUES (COL1 CHARACTER VARYING) = ROW(SUBSTRING('hello' FROM 3 USING CHARACTERS))

EXPLAIN VALUES SUBSTRING('hello world' FROM 3 FOR 5);
-- EXPLAIN: VALUES (COL1 CHARACTER VARYING) = ROW(SUBSTRING('hello world' FROM 3 FOR 5 USING CHARACTERS))

EXPLAIN VALUES SUBSTRING('hello world' FROM 3 USING CHARACTERS);
-- EXPLAIN: VALUES (COL1 CHARACTER VARYING) = ROW(SUBSTRING('hello world' FROM 3 USING CHARACTERS))

EXPLAIN VALUES SUBSTRING('hello world' FROM 3 FOR 5 USING CHARACTERS);
-- EXPLAIN: VALUES (COL1 CHARACTER VARYING) = ROW(SUBSTRING('hello world' FROM 3 FOR 5 USING CHARACTERS))

EXPLAIN VALUES SUBSTRING('hello world' FROM 3 FOR 2 + 3 USING OCTETS);
-- EXPLAIN: VALUES (COL1 CHARACTER VARYING) = ROW(SUBSTRING('hello world' FROM 3 FOR 2 + 3 USING OCTETS))

VALUES SUBSTRING('hello' FROM 0);
-- COL1:

VALUES SUBSTRING('hello' FROM 2);
-- COL1: ello

VALUES SUBSTRING('hello' FROM 4);
-- COL1: lo

VALUES SUBSTRING('hello' FROM 5);
-- COL1: o

VALUES SUBSTRING('hello' FROM 6);
-- COL1:

VALUES SUBSTRING('hello' FROM 20);
-- COL1:

VALUES SUBSTRING('hello' FROM -1);
-- COL1:

VALUES SUBSTRING('hello world' FROM 3 FOR 5);
-- COL1: llo w

VALUES SUBSTRING('hello world' FROM 3 USING CHARACTERS);
-- COL1: llo world

VALUES SUBSTRING('hello world' FROM 3 FOR 5 USING CHARACTERS);
-- COL1: llo w

VALUES SUBSTRING('Жabڣc' FROM 1);
-- COL1: Жabڣc

VALUES SUBSTRING('Жabڣc' FROM 2);
-- COL1: abڣc

VALUES SUBSTRING('Жabڣc' FROM 1 FOR 1);
-- COL1: Ж

VALUES SUBSTRING('Жabڣc' FROM 1 FOR 2);
-- COL1: Жa

VALUES SUBSTRING('Жabڣc' FROM 3 USING OCTETS);
-- COL1: abڣc

VALUES SUBSTRING('Жabڣc' FROM 4 USING OCTETS);
-- COL1: bڣc

VALUES SUBSTRING('Жabڣc' FROM 1 FOR 2 USING OCTETS);
-- COL1: Ж

VALUES SUBSTRING('Жabڣc' FROM 3 FOR 2 USING OCTETS);
-- COL1: ab
