#!/bin/sh

set -e

VSQL_FILE="$(mktemp).vsql" || exit 1
SQL_FILE="$(mktemp).sql" || exit 1

echo 'CREATE SEQUENCE seq1 START WITH 123 INCREMENT BY 5 MINVALUE 10 NO MAXVALUE;' | $VSQL in $VSQL_FILE
echo 'CREATE TABLE foo (bar INT);' | $VSQL in $VSQL_FILE

$VSQL out $VSQL_FILE > $SQL_FILE

grep -R "CREATE TABLE PUBLIC.FOO" $SQL_FILE
grep -R "CREATE SEQUENCE PUBLIC.SEQ1 START WITH 118 INCREMENT BY 5 MINVALUE 10;" $SQL_FILE
